export const FETCH_CHARACTERS = 'FETCH_CHARACTERS'
export const FETCH_EPISODES = 'FETCH_EPISODES'
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS'

export const FIND_EPISODE = 'FIND_EPISODE'
export const FIND_CHARACTER = 'FIND_CHARACTER'
export const FIND_LOCATION = 'FIND_LOCATION'
