export const FETCH_CHARACTERS = 'FETCH_CHARACTERS'
export const FETCH_EPISODES = 'FETCH_EPISODES'
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS'

export const FETCH_CHARACTERS_FOR_EPISODE = 'FETCH_CHARACTERS_FOR_EPISODE'
export const FETCH_CHARACTERS_FOR_LOCATION = 'FETCH_CHARACTERS_FOR_LOCATION'
export const FETCH_EPISODES_FOR_CHARACTER = 'FETCH_EPISODES_FOR_CHARACTER'